I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 116, in script
    with dissolve
Exception: Required parameter points has no value.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 116, in script
    with dissolve
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/ast.py", line 1275, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/exports.py", line 1381, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 2096, in do_with
    clear=clear)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 2793, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/screen.py", line 399, in visit_all
    callback(self)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/core.py", line 2793, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/screen.py", line 409, in per_interact
    self.update()
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/display/screen.py", line 578, in update
    self.screen.function(**self.scope)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/ast.py", line 152, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "/Users/yeelissa/Documents/renpy-pandamonium/renpy/ast.py", line 120, in apply
    raise Exception("Required parameter %s has no value." % name)
Exception: Required parameter points has no value.

Darwin-17.3.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Pandamonium 1.0
